name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install EB CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          pip3 install --user awsebcli
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Build Package Push with Maven
        working-directory: ./backend
        run: mvn -ntp -B verify -Ddocker.image.tag=${{ steps.build-number.outputs.BUILD_NUMBER }} jib:build

      # Set up AWS CLI credentials
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.EB_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker ${{ secrets.EB_APPLICATION_NAME }} --region ${{ secrets.EB_REGION }}
          sleep 5
          eb use ${{ secrets.EB_ENVIRONMENT_NAME }}
          sleep 5
          eb deploy --staged --region ${{ secrets.EB_REGION }}

      - name: Commit and push docker-compose.yml
        working-directory: ./backend
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docker-compose.yml
          git commit -m "Update docker-compose.yml with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push
